//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestVisicooler
    {
        public int id { get; set; }
        public Nullable<int> ReqID { get; set; }
        public string RegionName { get; set; }
        public string AreaName { get; set; }
        public string CeAreaName { get; set; }
        public string DbName { get; set; }
        public string cluster { get; set; }
        public string PSRName { get; set; }
        public string SubRoute { get; set; }
        public Nullable<int> OutletCode { get; set; }
        public string OutLetName { get; set; }
        public string Address { get; set; }
        public string OwnerName { get; set; }
        public string ContactNum { get; set; }
        public string ContactNumTwo { get; set; }
        public Nullable<bool> HaveVisicooler { get; set; }
        public string ChannelName { get; set; }
        public string OutletCatagoryName { get; set; }
        public string visicooleNeed { get; set; }
        public string remarks { get; set; }
        public string AppFlag1 { get; set; }
        public string AppFlag2 { get; set; }
        public string AppFlag3 { get; set; }
        public string AppFlag4 { get; set; }
        public string AppFlag5 { get; set; }
        public string AppFlag6 { get; set; }
        public string SE { get; set; }
        public string ASM { get; set; }
        public string RSM { get; set; }
        public string MEM { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string NightGuard { get; set; }
        public Nullable<int> VisiSize { get; set; }
        public string NewVisiSize { get; set; }
        public Nullable<System.DateTime> installDate { get; set; }
        public string VisiCode { get; set; }
        public string SEAck { get; set; }
        public string TotalCase { get; set; }
        public string VisiApplicationImg { get; set; }
        public string TradeLicenseImg { get; set; }
        public string VoterIDImg { get; set; }
        public string DeedCopyImg { get; set; }
    }
}
