//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        public int id { get; set; }
        public int VenID { get; set; }
        public string VendorName { get; set; }
        public string VendorAddress { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
